openapi: 3.0.3
info:
  title: Toy Manager API
  description: API for managing toys
  version: "1.0"
paths:
  /toys/available:
    get:
      summary: Get available toys
      description: Returns a list of available toy names
      responses:
        '200':
          description: A JSON array of toy names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Invalid Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Unexpected Error